[package]
name = "slint-webcam"
version = "1.0.0"
edition = "2021"

[dependencies]
slint = "1.2.2"
anyhow = "1"
image = "0.24.7"
rfd = "0.12.1"

[dependencies.nokhwa]
version = "0.10.4"
features = ["input-native"]